# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Linkr Blog
tagline:             "Link better, advance further"
description:         We are engaging for highly efficient professional social network!
url:                 http://blog.gotolinkr.com
baseurl:             /
paginate:            5
# About/contact
author:
  name:              linkr
  url:               http://www.gotolinkr.com/
  email:             support@gotolinkr.com

# Custom vars
version:             1.0.0

gems:
  - jekyll-sitemap